#ifndef CJ4ME_FEATURE_H
#define CJ4ME_FEATURE_H

#include <stdbool.h>

#include "cjong4/core/action.h"
#include "cjong4/core/rules.h"
#include "cjong4/manager/player_view.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CJ4ME_FEATURE_SCHEMA_VERSION 2u

enum {
  CJ4ME_FEATURE_HAND_OFFSET = 0,
  CJ4ME_FEATURE_HAND_COUNT = 34,

  CJ4ME_FEATURE_DISCARD_COUNT_OFFSET = 34,
  CJ4ME_FEATURE_DISCARD_COUNT_COUNT = 4 * 34,
  CJ4ME_FEATURE_DISCARD_TSUMOGIRI_OFFSET = 170,
  CJ4ME_FEATURE_DISCARD_TSUMOGIRI_COUNT = 4 * 34,
  CJ4ME_FEATURE_DISCARD_RIICHI_OFFSET = 306,
  CJ4ME_FEATURE_DISCARD_RIICHI_COUNT = 4 * 34,
  CJ4ME_FEATURE_DISCARD_ORDER_OFFSET = 442,
  CJ4ME_FEATURE_DISCARD_ORDER_COUNT = 4 * 34,

  CJ4ME_FEATURE_MELD_TILE_OFFSET = 578,
  CJ4ME_FEATURE_MELD_TILE_COUNT = 4 * 34,
  CJ4ME_FEATURE_MELD_TYPE_OFFSET = 714,
  CJ4ME_FEATURE_MELD_TYPE_COUNT = 4 * 5,

  CJ4ME_FEATURE_DORA_OFFSET = 734,
  CJ4ME_FEATURE_DORA_COUNT = 34,

  CJ4ME_FEATURE_DRAW_TILE_OFFSET = 768,
  CJ4ME_FEATURE_LAST_DISCARD_OFFSET = 803,
  CJ4ME_FEATURE_KAN_TILE_OFFSET = 838,
  CJ4ME_FEATURE_OPTIONAL_TILE_COUNT = 35,

  CJ4ME_FEATURE_SCORE_OFFSET = 873,
  CJ4ME_FEATURE_SCORE_COUNT = 4,
  CJ4ME_FEATURE_CURRENT_PLAYER_OFFSET = 877,
  CJ4ME_FEATURE_CURRENT_PLAYER_COUNT = 4,
  CJ4ME_FEATURE_DEALER_OFFSET = 881,
  CJ4ME_FEATURE_DEALER_COUNT = 4,
  CJ4ME_FEATURE_ROUND_WIND_OFFSET = 885,
  CJ4ME_FEATURE_ROUND_WIND_COUNT = 4,
  CJ4ME_FEATURE_PHASE_OFFSET = 889,
  CJ4ME_FEATURE_PHASE_COUNT = 8,
  CJ4ME_FEATURE_HONBA_OFFSET = 897,
  CJ4ME_FEATURE_RIICHI_STICKS_OFFSET = 898,
  CJ4ME_FEATURE_RIICHI_STATE_OFFSET = 899,
  CJ4ME_FEATURE_RIICHI_STATE_COUNT = 4,
  CJ4ME_FEATURE_SELF_FLAGS_OFFSET = 903,
  CJ4ME_FEATURE_SELF_FLAGS_COUNT = 3,

  CJ4ME_FEATURE_ACTION_TYPE_OFFSET = 906,
  CJ4ME_FEATURE_ACTION_TYPE_COUNT = 11,
  CJ4ME_FEATURE_ACTION_PLAYER_OFFSET = 917,
  CJ4ME_FEATURE_ACTION_PLAYER_COUNT = 4,
  CJ4ME_FEATURE_ACTION_TILE_OFFSET = 921,
  CJ4ME_FEATURE_ACTION_TILE_COUNT = 35,
  CJ4ME_FEATURE_ACTION_TILES_OFFSET = 956,
  CJ4ME_FEATURE_ACTION_TILES_COUNT = 34,
  CJ4ME_FEATURE_ACTION_TILE_COUNT_OFFSET = 990,

  CJ4ME_FEATURE_HAND_AKA_OFFSET = 991,
  CJ4ME_FEATURE_HAND_AKA_COUNT = 34,
  CJ4ME_FEATURE_DISCARD_AKA_OFFSET = 1025,
  CJ4ME_FEATURE_DISCARD_AKA_COUNT = 4 * 34,
  CJ4ME_FEATURE_MELD_AKA_OFFSET = 1161,
  CJ4ME_FEATURE_MELD_AKA_COUNT = 4 * 34,
  CJ4ME_FEATURE_DORA_AKA_OFFSET = 1297,
  CJ4ME_FEATURE_DORA_AKA_COUNT = 34,
  CJ4ME_FEATURE_DRAW_TILE_AKA_OFFSET = 1331,
  CJ4ME_FEATURE_LAST_DISCARD_AKA_OFFSET = 1332,
  CJ4ME_FEATURE_KAN_TILE_AKA_OFFSET = 1333,
  CJ4ME_FEATURE_ACTION_TILE_AKA_OFFSET = 1334,
  CJ4ME_FEATURE_ACTION_TILES_AKA_OFFSET = 1335,
  CJ4ME_FEATURE_ACTION_TILES_AKA_COUNT = 34,

  CJ4ME_FEATURE_COUNT = 1369
};

/**
 * Encodes one visible player view, its public rules, and one offered action.
 *
 * Returns false when an input enum, player, tile, or action count is
 * invalid. On failure, out_features is cleared when it is non-NULL.
 */
bool cj4me_encode_features(const cj4_player_view *view, const cj4_rules *rules,
                           const cj4_action *action,
                           float out_features[CJ4ME_FEATURE_COUNT]);

#ifdef __cplusplus
}
#endif

#endif /* CJ4ME_FEATURE_H */
