#ifndef CJ4ME_FEATURE_H
#define CJ4ME_FEATURE_H

#include <stdbool.h>
#include <stddef.h>

#include "cjong4/core/action.h"
#include "cjong4/core/rules.h"
#include "cjong4/manager/player_view.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CJ4ME_FEATURE_SCHEMA_VERSION 3u

enum {
  CJ4ME_TILE_COUNT = CJ4_TILE_ID_COUNT,
  CJ4ME_TILE_FEATURE_COUNT = 13,
  CJ4ME_TILE_EMBEDDING_COUNT = 8,

  CJ4ME_TILE_FEATURE_WALL = 0,
  CJ4ME_TILE_FEATURE_DISCARD = 1,
  CJ4ME_TILE_FEATURE_TSUMOGIRI = 2,
  CJ4ME_TILE_FEATURE_DISCARD_HISTORY = 3,
  CJ4ME_TILE_FEATURE_RIICHI_DISCARD = 4,
  CJ4ME_TILE_FEATURE_HAND_OWNER = 5,
  CJ4ME_TILE_FEATURE_MELD = 6,
  CJ4ME_TILE_FEATURE_AKA = 7,
  CJ4ME_TILE_FEATURE_DRAW = 8,
  CJ4ME_TILE_FEATURE_LAST_DISCARD = 9,
  CJ4ME_TILE_FEATURE_KAN = 10,
  CJ4ME_TILE_FEATURE_ACTION_PRIMARY = 11,
  CJ4ME_TILE_FEATURE_ACTION_MEMBER = 12,

  CJ4ME_FEATURE_TILE_OFFSET = 0,
  CJ4ME_FEATURE_TILE_COUNT = CJ4ME_TILE_COUNT * CJ4ME_TILE_FEATURE_COUNT,

  CJ4ME_FEATURE_SCORE_OFFSET = CJ4ME_FEATURE_TILE_COUNT,
  CJ4ME_FEATURE_SCORE_COUNT = 4,
  CJ4ME_FEATURE_PHASE_OFFSET = CJ4ME_FEATURE_SCORE_OFFSET + 4,
  CJ4ME_FEATURE_PHASE_COUNT = 8,
  CJ4ME_FEATURE_CURRENT_PLAYER_OFFSET = CJ4ME_FEATURE_PHASE_OFFSET + 8,
  CJ4ME_FEATURE_CURRENT_PLAYER_COUNT = 4,
  CJ4ME_FEATURE_DEALER_OFFSET = CJ4ME_FEATURE_CURRENT_PLAYER_OFFSET + 4,
  CJ4ME_FEATURE_DEALER_COUNT = 4,
  CJ4ME_FEATURE_ROUND_WIND_OFFSET = CJ4ME_FEATURE_DEALER_OFFSET + 4,
  CJ4ME_FEATURE_ROUND_WIND_COUNT = 4,
  CJ4ME_FEATURE_HONBA_OFFSET = CJ4ME_FEATURE_ROUND_WIND_OFFSET + 4,
  CJ4ME_FEATURE_RIICHI_STICKS_OFFSET = CJ4ME_FEATURE_HONBA_OFFSET + 1,
  CJ4ME_FEATURE_RIICHI_STATE_OFFSET = CJ4ME_FEATURE_RIICHI_STICKS_OFFSET + 1,
  CJ4ME_FEATURE_RIICHI_STATE_COUNT = 4,
  CJ4ME_FEATURE_SELF_FLAGS_OFFSET = CJ4ME_FEATURE_RIICHI_STATE_OFFSET + 4,
  CJ4ME_FEATURE_SELF_FLAGS_COUNT = 3,
  CJ4ME_FEATURE_STATE_COUNT = 33,

  CJ4ME_FEATURE_ACTION_OFFSET = CJ4ME_FEATURE_SELF_FLAGS_OFFSET + 3,
  CJ4ME_FEATURE_ACTION_TYPE_OFFSET = CJ4ME_FEATURE_ACTION_OFFSET,
  CJ4ME_FEATURE_ACTION_TILE_COUNT_OFFSET = CJ4ME_FEATURE_ACTION_OFFSET + 1,
  CJ4ME_FEATURE_ACTION_COUNT = 2,

  CJ4ME_FEATURE_COUNT =
      CJ4ME_FEATURE_ACTION_OFFSET + CJ4ME_FEATURE_ACTION_COUNT,
  CJ4ME_FEATURE_CONTEXT_OFFSET = CJ4ME_FEATURE_SCORE_OFFSET,
  CJ4ME_FEATURE_CONTEXT_COUNT =
      CJ4ME_FEATURE_STATE_COUNT + CJ4ME_FEATURE_ACTION_COUNT,
  CJ4ME_SCORE_INPUT_COUNT = CJ4ME_TILE_COUNT * CJ4ME_TILE_EMBEDDING_COUNT +
                            CJ4ME_FEATURE_CONTEXT_COUNT
};

#define CJ4ME_TILE_FEATURE_INDEX(tile, feature)                                \
  (CJ4ME_FEATURE_TILE_OFFSET + (size_t)(tile) * CJ4ME_TILE_FEATURE_COUNT +     \
   (size_t)(feature))

/**
 * Encodes one visible player view, public red-tile markers, and one offered
 * action using physical-tile feature schema v3.
 *
 * Returns false when an input enum, player, tile, location, or action count is
 * invalid. The action must belong to view->player. On failure, out_features is
 * cleared when it is non-NULL.
 */
bool cj4me_encode_features(const cj4_player_view *view, const cj4_rules *rules,
                           const cj4_action *action,
                           float out_features[CJ4ME_FEATURE_COUNT]);

#ifdef __cplusplus
}
#endif

#endif /* CJ4ME_FEATURE_H */
